### ISSUE TITLE
Include debugging instructions in MultiNodeTestRunner documentation

### ISSUE THREAD

**Issue by schatekar** [akkadotnet/getakka.net#111]
Link to documentation - https://github.com/akkadotnet/getakka.net/blob/master/src/docs/testing/multinode-testkit.md

Other details

https://files.gitter.im/akkadotnet/akka.net/fr2E/blob
https://files.gitter.im/akkadotnet/akka.net/K8m9/blob

**Comment by Aaronontheweb** [comment]
Make sure you download the files and include them locally in the https://github.com/akkadotnet/getakka.net/tree/master/src/docs/images/multinode-teskit folder

We should probably also crop that first screenshot :p
