### ISSUE TITLE
Broken "Edit on GitHub" link

### ISSUE THREAD

**Issue by memark** [akkadotnet/getakka.net#121]
This "Edit on GitHub" link on this page is broken and returns 404.

http://getakka.net/docs/deployment-scenarios/ASP%20NET

**Comment by memark** [comment]
Still broken.

**Comment by SeanKilleen** [comment]
Following up on this -- I believe the edit on github link is broken for any documents that are in a sub-folder within /src/docs, such as the "working with actors" sub-section or the "streams" sub-section.

I'll see if I can find a way to PR this.

**Comment by SeanKilleen** [comment]
The issue occurs [on line 13 of docs.hbs](https://github.com/akkadotnet/getakka.net/blob/ada0a4b3ac8acb86bd3c8d39971734d26e04a743/src/layouts/docs.hbs#L13)

The path assumes `/docs/{{ basename }}.md`. So either:

* the subfolder name needs to be determined as well
* the `basename` variable needs to be updated
* a variable other than `basename` needs to be used.

**Comment by SeanKilleen** [comment]
Per [the assemble.io docs](http://assemble.io/docs/Built-in-Variables.html):

> `{{ basename }}` returns the basename for the current page from the root of the context. Example: `{{basename 'index.html'}}`, returns "index".

There's also, `{{ dirname }}`, which is listed as "equivalent to node `path.dirname`".

So, it sounds like the solution to this will be something along the lines of:

* get `dirname`
* adjust that to be from `/docs` onward
* use the github path, plus the concatenated dirname, plus the basename.

**Comment by SeanKilleen** [comment]
@memark feel free to check out #246, checkout my branch, build locally, and see if it fixes your problem. :)

**Comment by SeanKilleen** [comment]
@memark FYI this is now fixed in production.

**Comment by memark** [comment]
@SeanKilleen The actual page URL is no longer valid, but I found a similar page, and there the link works. Thanks!
