### ISSUE TITLE
Add page with contributors plugins.

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/getakka.net#135]
We decided to add some page where we could listen contributor's plugins, which doesn't necessarily reside in akkadotnet organization. This way we could make them more discoverable to potential people interested in using them.

**Comment by Danthar** [comment]
I don't have a full overview of whats out there. But if we could make a list in here. That would help.

**Comment by Horusiath** [comment]
These are groups of plugins, that come to my mind:
- [Akka.Monitoring](https://github.com/Aaronontheweb/akka-monitoring) - monitoring plugins for Akka.NET actors.
- [Even](https://github.com/evendotnet/Even) - alternative approach to actors eventsourcing. 
- [Akka.Interfaced](https://github.com/SaladbowlCreative/Akka.Interfaced) - typed actors build upon interfaced RPC calls.
- [Akkling](https://github.com/Horusiath/Akkling) - alternative fork of Akka.NET F# API.

**Comment by Danthar** [comment]
What about all the other projects not in the core repo, but still in the organisation. Like the persistence plugins?
And once we moved out the logging and DI stuff, what about those ?

Or Akka.cluster.monitor. Its not really a plugin in the traditional sense of the word. But it does merit some mentioning imho.

And Wire ofcourse.
