### ISSUE TITLE
Port akka streams documentation

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/getakka.net#154]
The main index that serves as a starting point / guideline.
http://doc.akka.io/docs/akka/2.4.4/scala/stream/index.html

Ill be working on this. Ill create a PR for the some of the hooks in the main index page. Once thats done. Anyone is welcome to pick a subject to port and contribute to the overall process.

Post in here if you want to take a chunk of the work. And let us know which part your taking.

**Comment by Danthar** [comment]
Check https://github.com/akkadotnet/akka.net/pull/1935 for figuring out how the JVM api maps to our .NET port.
Its important that any JVM specific implementations are correctly translated to the port in Akka.NET.

**Comment by Danthar** [comment]
Here follows an outline of why some subject are not ported. Or perhaps warrant some extra attention.

**Not ported:** [Interoperation with other Reactive Streams implementations]
**Why:** There are no other implementations of reactive streams in .NET space, and Akka.NET streams probably won't interop with JVM implementations just yet.

**Misc:** [Reactive Tweets]
**Remarks:** Not sure if there is a feasible .NET twitter API available to reproduce this sample. Investigate once we get to porting this section. 

**Misc:** [Graph cycles, liveness and deadlocks]
**Remarks:** There is currently a known issue with the deadlock section in that subject. ref https://github.com/akkadotnet/akka.net/pull/1929

**Not Ported:** [Working with streamin IO] -> [Streaming TCP]
**Why:** Akka.IO is not ready to be integrated with the streaming api just yet. No sense in documenting something that does not work 'yet'.

**Comment by Danthar** [comment]
@Silv3rcircl3 is working on [Basics and working with Flows]

**Comment by marcpiechura** [comment]
I also take [Working with Graphs]

**Comment by marcpiechura** [comment]
and [Modularity, Composition and Hierarchy]

**Comment by Danthar** [comment]
Taking  [Buffers and working with rate] and [Custom stream processing]

**Comment by marcpiechura** [comment]
[Integration] and [Error handling]

**Comment by marcpiechura** [comment]
[Working with streaming IO] and [Pipelining and Parallelism]

**Comment by marcpiechura** [comment]
[Testing streams] and [Overview of built-in stages and their semantics]

**Comment by marcpiechura** [comment]
[Cookbook]

**Comment by Danthar** [comment]
Reactive tweets: This lib seems promising enough to base the reactive tweets sample on.
https://github.com/linvi/tweetinvi

**Comment by marcpiechura** [comment]
@danthar I created a simple demo project for this.

https://github.com/Silv3rcircl3/Akka.Net-Streams-reactive-tweets

**Comment by Danthar** [comment]
@Silv3rcircl3 Nice. Would you mind writing the Reactive Tweets chapter that goes with it? I feel you would better suited to write that chapter then me. Since you have made the sample ;)

**Comment by Danthar** [comment]
Custom stream processing text PR is waiting.

**Comment by Danthar** [comment]
Im closing this issue since all subjects have been ported.
