### ISSUE TITLE
Deployment scenario: Windows Service

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/getakka.net#17]
Porting from https://github.com/akkadotnet/akka.net/issues/656 since this lives in its own repo now:

On the [Deployment Scenarios page](http://getakka.net/wiki/Use%20case%20and%20Deployment%20Scenarios), I noticed there is an empty section for Windows Service.

Adding it here in case someone wants to take it on (may do so myself).

**Comment by Danthar** [comment]
Ill be working on creating a Windows Service host for an Akka.Net application tomorrow. I can probably do an PR for documentation about this at the end of the day.

**Comment by skotzko** [comment]
@Danthar @SeanKilleen if you want to pull from some already written material that leverages a Windows service, check out [this sample](https://github.com/petabridge/akkadotnet-code-samples/tree/master/Cluster.WebCrawler) that @Aaronontheweb and I put together using TopShelf.

**Comment by Danthar** [comment]
Created a pull request for this #36

**Comment by SeanKilleen** [comment]
Closing this as #36 was merged.
