### ISSUE TITLE
Deployment scenario: asp.net web site 

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/getakka.net#18]
Porting this from https://github.com/akkadotnet/akka.net/issues/655 as it's more germane here.

Initial issue text below.

---

On the [Deployment Scenarios page](http://getakka.net/wiki/Use%20case%20and%20Deployment%20Scenarios), I noticed there is an empty section for ASP.NET.

Adding it here in case someone wants to take it on (may do so myself).

**Comment by Danthar** [comment]
Made a PR #41

**Comment by SeanKilleen** [comment]
Closing this per PR #41 being merged.
