### ISSUE TITLE
Missing content in docs - handling messages

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/getakka.net#185]
[Handling messages](http://getakka.net/docs/working-with-actors/handling-messages) is pretty important topic for beginners, however it looks like it's still a blank page in our case.

**Comment by alexvaluyskiy** [comment]
@Horusiath I could take it. I've already converted some basic Akka documentation a couple months ago. I should make PR.
I've started from this PR https://github.com/akkadotnet/getakka.net/pull/186
