### ISSUE TITLE
Documentation links on website are broken

### ISSUE THREAD

**Issue by jpierson** [akkadotnet/getakka.net#188]
@jpierson commented on [Wed Jul 27 2016](https://github.com/akkadotnet/akka.net/issues/2216)

I wanted to contribute some documentation fixes for the page on [Remoting](http://getakka.net/docs/Remoting) but found that the [edit on GitHub link](https://github.com/akkadotnet/getakka.net/edit/master/src/docs/Remoting.md) yields a 404 error and when searching the repository for Remoting.md nothing could be found. I'm assuming that the documentation has been migrated out of some original GitHub Markdown files and placed somewhere else. Is the current documentation somewhere contributors can help with? Can the links be fixed to give a better impression of the project to newcomers and to direct contributors to where they can modify the documents?

By the way, the original change I wanted to make was to update some stale comments about "Akka I/O(Not yet ported to Akka.NET)".

---

@jpierson commented on [Wed Jul 27 2016](https://github.com/akkadotnet/akka.net/issues/2216#issuecomment-235480414)

Ok, I believe I've answered my own question on [where to contribute documentation changes on remoting](https://github.com/akkadotnet/getakka.net/blob/master/src/docs/remoting/index.md) but it looks like the documentation in question has already been corrected. This leads me to followup question though, why isn't the documentation updated on the site?

**Comment by jpierson** [comment]
![image](https://cloud.githubusercontent.com/assets/1467146/18146667/ea46bbea-6f9e-11e6-85a1-454e272ff190.png)

**Comment by Danthar** [comment]
Because the 2 are not linked. And people forget. 
But you are more then welcome to make PR's to improve things. :)

**Comment by jpierson** [comment]
@Danthar, What do you mean the 2 are not linked? I don't understand your point. Are you saying that the website and the markdown content are not linked?

**Comment by Danthar** [comment]
No im saying that the code repository where work on the library is being done. And the documentation website, are 2 separate things. So people place a PR in the code repository to change/update/fix something. But they don't update the website.

Ideally we would like a single PR to contain both things, the change in code, and the documentation update.
