### ISSUE TITLE
Docs do not mention one cannot handle PoisonPill as a regular message

### ISSUE THREAD

**Issue by troshko111** [akkadotnet/getakka.net#217]
When using pattern like The Reaper, it's very tempting to use `PoisonPill` as a stop notification (i.e. do a cleanup). Unfortunately, this does not seem to work as actors do not receive `PoisonPill` per se (seems to be handled by the framework). One may want to do some pre-stop cleanup on `PoisonPill` and the only option seems to be to enqueue some custom `Stop` message and do a cleanup, since there's no PreStop and one cannot "handle" `PoisonPill`.

Maybe it's just me, but it feels counter-intuitive that you cannot handle `PoisonPill`, I'd say it's worth explaining that in docs. Thoughts?

**Comment by Danthar** [comment]
I think its explained rather well here: http://getakka.net/docs/working-with-actors/stopping-actors ?

**Comment by troshko111** [comment]
@Danthar I'd say you're right, It's explained pretty well, but: most of the docs would say "`PoisonPill` is just a regular message" and this implies you can handle it If you wish, which is not true. So not that regular per se. There's only one place which suggests `PoisonPill` is auto handled and it would remove the ambiguity if the docs just said  `PoisonPill` cannot be handled by user code and clean up must be implemented by sending a custom message BEFORE sending `PoisonPill`. It's rather common to do some cleanup before graceful shutdown, and suggesting a way to do it in docs would be nice.

Maybe I'm being stupid but it took quite some time to scroll through GitHub/blogs/docs before I realized this
