### ISSUE TITLE
searching documentation in getakka.net in google gives blank page with error message

### ISSUE THREAD

**Issue by pavsh** [akkadotnet/getakka.net#251]
Hi,
for example if you searching for HOCON configuration you get a result in google  the following url: 
getakka.net/docs/concepts/configuration
 when accessing the url you getting a blank page with this message:

"the resource you are looking for has been removed, had its name changed, or is temporarily unavailable"
I suppose you changed the documentation site but  google's crawlers still finding it.
this is the screenshot from the search result:

![image](https://user-images.githubusercontent.com/5156780/29243013-2a569baa-7f9e-11e7-8ad0-171b8b02255a.png)

**Comment by Aaronontheweb** [comment]
We just updated the entire website last night: http://getakka.net/ - some of these URLs have been moved

**Comment by pavsh** [comment]
thank you for your fast reply. 

Are you plan to update the landing page message with some link to the new URLs or update the crawlers?
very hard to search this way for documentation.
