### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/getakka.net#27]
Running "compass:dist" (compass) task
Warning: Couldn't find the `compass` binary. Make sure it's installed and in your $PATH Use --force to continue.

cc @skotzko 

Where can I find copass binaries?

**Comment by skotzko** [comment]
le fixed... `rbenv rehash` ftw

**Comment by rogeralsing** [comment]
Still need a workaround on windows for local dev though :P
