### ISSUE TITLE
wiki and docs sections appear to be mirrors

### ISSUE THREAD

**Issue by sean-gilliam** [akkadotnet/getakka.net#57]
I think this is a leftover from when the docs were moved out of the main akka.net tree. It's not hurting anything at the moment since wiki/ isn't a direct link on the page, but if a user types wiki/ or another website points there...

I suggest either remove wiki/ or revamp it to something other than a mirror of docs/

**Comment by rogeralsing** [comment]
Wiki pages have been removed.
