### ISSUE TITLE
Dependency Injection page is missing a description about using the DI() extension

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/getakka.net#62]
In PR #60 some bits where removed from the `Dependency Injection.md` file. I am wondering if it was intentional or not. Because I think that the part in question is still relevant information. And if not on that page, it should at least be described somewhere else.

Its about this part:

```
Creating child Actors from inside an Actor can be done using the DI() extension method.
```

``` csharp
//In for example the PreStart...
protected override void PreStart()
{
    myWorker = Context.DI().ActorOf<TypedWorker>("childWorker");
}

```

**Comment by sean-gilliam** [comment]
It's part of [DI Core](http://getakka.net/docs/DI%20Core#creating-child-actors-using-di) unless I'm missing something.

**Comment by Danthar** [comment]
Ah you moved it. Missed that. :)

But I do not think it belongs there. The Dependency Injection page is all about how to _use_ DI in Akka. While the DI Core is about how to _implement_ your own DI extension for the framework.

When you want to use DI in Akka, its odd that the first page you find about this. Does explain how to use it from outside the ActorSystem, but does not tell you how to use it from _inside_ the actor system.
It feels like its hidden away now.

**Comment by sean-gilliam** [comment]
~~I didn't move it. It was always in DI Core. I was just trying to keep the documents DRY. Feel free to add it back in if you want or move it from DI Core to Dependency inject.~~

I see what you're saying now. I guess I got mixed up in my copy paste. I'll fix it here shortly.

**Comment by Danthar** [comment]
For the record. Your other stuff was really great. This is just a minor thing. :) @sean-gilliam

**Comment by sean-gilliam** [comment]
Thank you @Danthar. Just trying to clean up the documentation to be more accessible and helpful.
