### ISSUE TITLE
Reorganization of Akka.NET docs for v1

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/getakka.net#7]
Moved from https://github.com/akkadotnet/akka.net/issues/794 to here.
## Documentation Guidelines

Here are some rules and guidelines to follow when working on the updated docs.
- **Use the v1.0 APIs everywhere**, since they will be supported long-term. We just published a [pre-release V1 nuget package](https://www.nuget.org/packages/Akka/1.0.0-dev1504032244) to make this easier for writing compilable samples.
- **Replace any Java / Scala code from existing documents with relevant C# and F# samples.**
- **Use [.NET Fiddle](https://dotnetfiddle.net/) for any runnable samples** in the docs.
- **Include BOTH F# and C# samples** - if you need help with the F#, let @akkadotnet/fsharpteam know.
- **Draw diagrams where appropriate.** Most programmers are visual learners. They will love you for this.

All of the docs are written in Markdown format and are saved to the [/wiki directory](https://github.com/akkadotnet/akka.net/tree/dev/documentation/wiki) in this repo.
### This will take a lot of effort, so we need all the help we can get. Calling all @akkadotnet/contributors - pick some areas where you can help and send us some PRs for the documents there.

---
## Akka.NET v1.0 Documentation

This is what the table of contents will look like - all left-most items are _individual pages._ Anything that's indented further in can either be a section on that page or its own sub-page depending on whether or not the content is something that should be immediately visible to developers scanning the TOC.
## Introduction
- [ ] What is Akka.NET?
  - [ ] Akka & Typesafe
- [ ] Why Akka.NET?
- [ ] Akka.NET Quickstart
  - [ ] C# Quickstart
  - [ ] F# Quickstart
- [ ] What are some real-world use cases for Akka.NET? 
- [ ] FAQ
  - [ ] Mono Support
  - [ ] Remoting & Clustering
  - [ ] Contributing
  - [ ] Commercial Support
- [ ] Learning Resources
  - [ ] Akka.NET Bootcamp
  - [ ] OSS Akka.NET Examples
  - [ ] Videos
  - [ ] Blogs & Articles
  - [ ] Podcasts & Interviews
  - [ ] Talks and Presentations
## Akka.NET Concepts and Terminology
- [x] Terminology, Concepts
- [x] Actor Systems
- [x] What is an Actor?
- [x] What is a Message?
  - [x] Immutability
- [x] Supervision and Monitoring
- [x] Actor References, Paths, and Addresses
- [x] Location Transparency
- [x] Message Delivery Reliability
- [x] Configuration
## Working with Actors
- [ ] Creating your first Actor
  - [ ] C#
  - [ ] F#
- [ ] Defining an Actor class
  - [ ] ReceiveActor
  - [ ] UntypedActor
- [ ] What's in an actor?
  - [ ] State
  - [ ] Behavior(s)
  - [ ] Mailbox
  - [ ] Children
  - [ ] Supervisor Strategy
  - [ ] Context
- [ ] ActorRefs and ActorSelections
  - [ ] Location Transparency
  - [ ] Explan how actors can be restarted independently of actorrefs, and this is why they're cool
- [ ] Creating actors with Props
  - [ ] Props
    - [ ] What's the point?
    - [ ] Serializability
    - [ ] Role in restarts
  - [ ] System.ActorOf
  - [ ] Creating Children with Context.ActorOf
- [ ] Handling Messages
  - [ ] ReceiveActor
  - [ ] UntypedActor
    - [ ] if, else if, else - type interference
    - [ ] PatternMatch
- [ ] Sending Messages
  - [ ] Immutability
  - [ ] Tell
  - [ ] Ask
  - [ ] Forward
  - [ ] Replying to messages
- [ ] Looking up Actors
  - [ ] ActorSelection
- [ ] Stopping Actors
  - [ ] PoisonPill
  - [ ] Graceful Stop
- [ ] What happens when an actor dies?
  - [ ] Unplanned Termination ("Crashes")
    - [ ] Supervision strategies in action
    - [ ] Restarts
    - [ ] What happens to messages during restarts?
      - [ ] Unprocessed messages
      - [ ] Message that caused the restart
    - [ ] What happens to children during restarts?
  - [ ] Planned Termination
    - [ ] How to stop an actor
    - [ ] DeathWatch
      - [ ] What happens to messages during termination?
        - [ ] Unprocessed messages
        - [ ] Message that caused the restart
    - [ ] What happens to children after termination?
- [ ] The Actor Lifecycle
  - [ ] PreStart
  - [ ] PreRestart
  - [ ] PostStop
  - [ ] PostRestart
  - [ ] DeathWatch
- [x] Dispatchers
  - [x] What Dispatchers Do
  - [x] Types of Dispatchers
    - [x] ThreadPoolDispatcher (default)
    - [x] ForkJoinDispatcher
    - [x] SynchronizedDispatcher
    - [x] SingleThreadDispatcher
    - [x] TaskDispatcher
  - [ ] Custom Dispatchers
- [x] Mailboxes
  - [x] What Mailboxes Do
  - [x] Types of Mailboxes
    - [x] UnboundedMailbox (default)
    - [x] PriorityMailbox
  - [x] Custom Mailboxes
- [x] Switchable Behaviors
  - [x] Become
  - [x] BecomeStacked
  - [x] UnbecomeStacked
- [x] Stashing Messages
  - [x] Bounded Stash
  - [x] Unbounded Stash
- [ ] Detecting Failures with ReceiveTimeout
- [ ] Dependency Injection and Actors
  - [ ] Ninject
  - [ ] Autofac
  - [ ] Castle Windsor
- [ ] Routers
  - [ ] Pool vs. Group
    - [ ] Supervision
  - [ ] RoundRobin
  - [ ] Broadcast
  - [ ] Random
  - [ ] ConsistentHash
  - [ ] TailChopping
  - [ ] SmallestMailbox
## Configuration
- [ ] Using Akka.NET Config (HOCON) in Production
  - [ ] Fallbacks
  - [ ] App.config & Web.config
  - [ ] Parsing Configuration from Strings
- [ ] Configuring Akka.NET Modules
  - [ ] Akka.Remote
  - [ ] Akka.Cluster
  - [ ] Akka.Persistence
- [ ] Configuring Loggers
  -  [ ] Logging Options
  -  [ ] Serilog
  -  [ ] NLog
  -  [ ] Custom Loggers
## ActorSystems & Utilities
- [ ] Finite State Machines (FSM)
- [ ] EventBus
- [ ] Scheduler
  - [ ] Scheduling Recurring Messages
  - [ ] Canceling a Recurring Message
  - [ ] Scheduling a One-time Message
- [ ] Inbox
- [ ] ActorSystem Extensions
  - [ ] Using ActorSystem Extensions
  - [ ] Creating ActorSystem Extensions
- [ ] Extending the Actor Construction Pipeline
  - [ ] What does the Actor Construction Pipeline do?
  - [ ] Use Cases
  - [ ] Examples
## Unit Testing Your Actors
- [ ] Using Akka.TestKit
  - [ ] With XUnit
  - [ ] With MSTest
- [ ] Writing Testable Actors
- [ ] TestKit Tools
  - [ ] TestActor
  - [ ] Expecting Messages
  - [ ] TestProbe
  - [ ] EventFilter
## Akka.Remote (Networked ActorSystems)
- [x] Remoting Overview
  - [x] Remote Addressing
  - [x] How Remote Connections Form
  - [x] Transports
  - [x] Location Transparency
- [x] Serialization
- [x] Transports
  - [x] Helios
    - [x] TCP
    - [ ] UDP (in the future)
  - [x] Custom Transports
- [x] Sending Messages to Remote Actors
  - [ ] What happens when a connection dies?
- [x] Deploying Actors onto Remote Systems
  - [ ] What happens to remotely deployed actors when a connection dies?
  - [x] Remote DeathWatch
- [ ] Remoting Configuration
## Akka.Cluster (Clustered ActorSystems)
- [x] Clustering Overview
  - [x] How is Clustering different from Remoting?
  - [x] How a Cluster Forms
    - [x] Seed Nodes
    - [x] Gossip
    - [x] Leader Election
    - [x] Reachability
  - [x] Location Transparency
- [x] Cluster Routing
  - [x] Deploying Clustered Routees
  - [x] Configured Cluster Routers
- [x] Cluster ActorSystem Extension
  - [x] Getting Cluster State
  - [x] Subscribing to Cluster Events
  - [x] Cluster Event Types
    - [x] Reachability
    - [x] MemberUp / MemberDown
- [x] Cluster Configuration
## Akka.Persistence (Guaranteed Message Delivery, Persistent Actors)
- [ ] Persistence Overview
  - [ ] Goals of Persistence
  - [ ] Snapshots
  - [ ] Journals
  - [ ] Persistence Plugins
    - [ ] SQL Server
    - [ ] File System
- [ ] Guaranteed Delivery of Messages
- [ ] Creating your own Persistent Actors
- [ ] Creating your own Persistence Target
- [ ] Persistence Configuration
## Information for Akka Developers
- [x] Building and Distributing Akka.NET
- [ ] Contributor guidelines
- [x] Documentation Guidelines
- [x] Team
## Project Information
- [ ] Licenses
- [ ] Sponsors
- [ ] Project
## Additional Information
- [ ] FAQ
- [ ] Online resources
- [ ] Books
- [ ] Commercial Support & Training

**Comment by Aaronontheweb** [comment]
@skotzko here's where I would like your help:

Section: `Working with Actors`
- [ ] Creating your first Actor
  - [ ] C#
  - [ ] F#
- [ ] Defining an Actor class
  - [ ] ReceiveActor
  - [ ] UntypedActor
- [ ] What's in an actor?
  - [ ] State
  - [ ] Behavior(s)
  - [ ] Mailbox
  - [ ] Children
  - [ ] Supervisor Strategy
  - [ ] Context
- [ ] ActorRefs and ActorSelections
  - [ ] Location Transparency
  - [ ] Explan how actors can be restarted independently of actorrefs, and this is why they're cool
- [ ] Creating actors with Props
  - [ ] Props
    - [ ] What's the point?
    - [ ] Serializability
    - [ ] Role in restarts
  - [ ] System.ActorOf
  - [ ] Creating Children with Context.ActorOf
- [ ] Handling Messages
  - [ ] ReceiveActor
  - [ ] UntypedActor
    - [ ] if, else if, else - type interference
    - [ ] PatternMatch
- [ ] Sending Messages
  - [ ] Immutability
  - [ ] Tell
  - [ ] Ask
  - [ ] Forward
  - [ ] Replying to messages

---

Mind taking that on so I can start work on the remoting docs?

**Comment by skotzko** [comment]
@Aaronontheweb got it. I will take those on.

**Comment by Aaronontheweb** [comment]
I'm going to get started on remoting stuff

**Comment by Aaronontheweb** [comment]
I think we actually cover the "What is an Actor" twice - I'm using the current definition inside the `Concepts` section. We won't need the same thing again inside the `Working with Actors` section @skotzko

**Comment by nvivo** [comment]
I'll fix the "Working with Actors > Routers" section.

**Comment by nvivo** [comment]
Starting to look at "Stashing Messages" and "Switchable Behaviors"

**Comment by nvivo** [comment]
I'll take Mailboxes now.

**Comment by nvivo** [comment]
Working on dispatchers.

**Comment by Danthar** [comment]
Ill take on Dependency Injection and Actors 
Besides an overhaul so its reflects the 1.0 api, it could use some extra information about lifetime scopes of the actors.

**Comment by Danthar** [comment]
https://github.com/Danthar/getakka.net/blob/master/src/docs/Dependency%20injection.md

So what I did is add examples for the 1.0 API and how to resolve Actor types from inside an Actor. 
I also wanted to make it more explicit which type of lifestyle scopes (in regards to the DI container) are supported and what not.
However I am still not happy with how it turned out at the moment. But I cant put my finger on what it is I don't like. So I am not doing a PR just yet.

If some of you guys could look it over and provide some feedback. That would be great.

**Comment by nvivo** [comment]
Grabbing the Actor Lifecycle.

**Comment by nvivo** [comment]
Just to let anyone know, I got quite busy lately, so I had to take a break. I'm not working on the Actor Lifecycle anymore.

**Comment by sean-gilliam** [comment]
There appears to be some duplication in the list i.e. Configuration, Resources FAQ, etc. How should we handle that in our PRs? Section > topic > subtopic? More detailed topic comes first?

**Comment by Danthar** [comment]
Im working on the 'Working with Actors' bit. I am doing some restructuring to put things in line with what @Aaronontheweb has outlined. And I will in some blanks here and there. I will document my changes so that we will have a good idea of what still needs to be done after my PR.

**Comment by Danthar** [comment]
Made a PR #97 Feedback wanted

**Comment by skotzko** [comment]
I'll be diving into the Clustering docs tomorrow. / cc @Aaronontheweb

**Comment by Aaronontheweb** [comment]
Starting work on Remoting docs

**Comment by skotzko** [comment]
started on Cluster docs
