### ISSUE TITLE
http://getakka.net/docs/IO

### ISSUE THREAD

**Issue by nibblesnbits** [akkadotnet/getakka.net#90]
This documentation page seems like something I need, but it seems the only place this code exists is [here](https://github.com/willieferguson/akka.net/tree/c99a044d89cbb3ece8df0c0c8e7a9aafd3fba6c6/src/core/Akka/IO), which hasn't been merged into the akkadotnet repo.  Is there a projected date on when this will become available?

**Comment by fergusn** [comment]
@nibblesnbits The IO extension is in the [akka-io branch](https://github.com/akkadotnet/akka.net/tree/akka-io). 

It should be merged into the dev branch in the next couple of days - I need to complete some documentation before it can be merged.

**Comment by nibblesnbits** [comment]
Good to hear.  I look forward to release.
