### ISSUE TITLE
Please remove smoothscroll from body classes

### ISSUE THREAD

**Issue by balefrost** [akkadotnet/getakka.net#93]
As a trackpad user, I find sites that use smoothscroll (a Javascript library) to be very awkward to navigate. Smoothscroll appears to animate every page scroll. I think this is supposed to provide a better user experience, but it creates these problems.
1. It adds a delay when scrolling with the trackpad. My trackpad and browser already support both fine scrolling and inertial scroll. Smoothscroll works to undermine both of these mechanisms. On most sites, when I stop moving my fingers, scrolling also stops. And when I've flung the page, placing my fingers back on the trackpad stops the scroll. Neither of these behaviors are true on pages with smoothscroll. Instead, I'm constantly overshooting my scrolling. 
2. It's even worse with a scroll wheel mouse. Smoothscroll seems to buffer the actual wheel events, and "plays them back" over time. So I might be moving the wheel up, but I instead see the page scroll down. 

Smoothscroll is bad for both trackpad and mouse users. It makes everything delayed and laggy and terrible. Personally, it makes me feel drunk. Please remove it. 

It looks like this can be done by simply removing the smoothscroll class from src/layouts/master.hbs

**Comment by Aaronontheweb** [comment]
Thoughts on this @skotzko ?

**Comment by Danthar** [comment]
has already been removed via a PR
